---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: ca-issuer
  namespace: openfaas
spec:
  ca:
    secretName: ca-key-pair
---

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gateway
  namespace: openfaas
spec:
  secretName: gateway-tls
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
  commonName: davidamarshall.me
  organization:
  - David Marshall
  dnsNames:
  - gateway.davidamarshall.me
---
