apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: k8s.gcr.io/metrics-server-amd64 # match images with this name
    newName: k8s.gcr.io/metrics-server-arm64 # override the name
resources:
- metrics-server-deployment.yaml
