#!/usr/bin/awk -f

BEGIN {
	# output comment for generated lines
	printf("cat >> /etc/hosts <<EOF\n")
	printf("#auto-generated by rpigenhosts\n")
}

NR==1 {
	split($1,colnames,",")
}
NR > 1 {
	split($1,vals, ",")
	clusterip = vals[3]
	hostname  = vals[2]
	printf("%s\t%s\n", clusterip, hostname)
}

END {
	printf("EOF\n")
}
