apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/jetstack/cert-manager-cainjector
    newName: quay.io/jetstack/cert-manager-cainjector-arm64
  - name: quay.io/jetstack/cert-manager-controller
    newName: quay.io/jetstack/cert-manager-controller-arm64
  - name: quay.io/jetstack/cert-manager-webhook
    newName: quay.io/jetstack/cert-manager-webhook-arm64
resources:
- cert-manager.yaml
