apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    newName: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm64
resources:
- mandatory.yaml
- service-loadbalancer.yaml
